title: Workflow
sites:
  - en
propagate: false
template: default
layout: layout
revisions: false
route: '/feature-experiment/workflow/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
inject:
  nav_title: experiment
  landing: true
structure:
  root: false
