title: Workflow
propagate: false
template: default
layout: layout
taxonomies:
  - experiment_type
revisions: false
route: '/experiment/workflow/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
inject:
  nav_title: experiment
  landing: true
structure:
  root: false
